### ISSUE TITLE
remove python cherrypy from install script

### ISSUE THREAD

**Issue by Hellowlol** [EZarnosky/Bandito#1]
https://github.com/EZarnosky/Bandito/blob/master/modules/install-htpcmanager.sh#L6

You can remove python-cherrypy from that line, its already included the project :) (dunno why some guides includes it)

**Comment by EZarnosky** [comment]
Shall do, I am hacking and slahing my way though all these various guides, trying to get something that works everytime. I am cleaning off the cobwebs, its been a LONG time since I have played with shell scripts.

**Comment by Hellowlol** [comment]
I dont even understand any shell script so your doing better then me :D
